# Generated by Django 5.2.1 on 2025-05-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_member_delete_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('téléphone', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
