# Generated by Django 5.2.1 on 2025-05-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_devis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devis',
        ),
    ]
