# Generated by Django 5.2.1 on 2025-06-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_cree_par'),
        ('clients', '0006_delete_devis'),
    ]

    operations = [
    ]
