# Generated by Django 5.2.1 on 2025-06-02 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_merge_0002_add_cree_par_0006_delete_devis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, help_text='Adresse postale complète', null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cree_par',
            field=models.ForeignKey(help_text='Utilisateur ayant créé le client', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure de création du client', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text='Adresse email de contact principale', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(help_text="Nom complet du client ou de l'entreprise", max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes additionnelles sur le client', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='téléphone',
            field=models.CharField(help_text='Numéro de téléphone de contact', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['nom'], name='clients_cli_nom_0cf00c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'),
        ),
    ]
