# Generated by Django 5.2.1 on 2025-06-02 07:30

import devis.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0008_remove_montant_ttc_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Numéro unique du devis', max_length=20, null=True, unique=True, verbose_name='Numéro')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création du devis', verbose_name='Date de création')),
                ('date_validite', models.DateField(default=devis.models.get_default_date_validite, help_text="Date jusqu'à laquelle le devis est valable", verbose_name='Date de validité')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, help_text='Montant total hors taxes', max_digits=10, verbose_name='Montant HT')),
                ('conditions_paiement', models.TextField(help_text='Conditions de paiement spécifiées', verbose_name='Conditions de paiement')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur le devis', null=True, verbose_name='Notes')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='brouillon', help_text='État actuel du devis', max_length=20, verbose_name='Statut')),
                ('client', models.ForeignKey(help_text='Client concerné par le devis', on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='clients.client', verbose_name='Client')),
                ('cree_par', models.ForeignKey(help_text='Utilisateur ayant créé le devis', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description détaillée du produit ou service', verbose_name='Description')),
                ('quantite', models.PositiveIntegerField(help_text='Quantité commandée', verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix unitaire hors taxes', max_digits=10, verbose_name='Prix unitaire')),
                ('montant', models.DecimalField(decimal_places=2, editable=False, help_text='Montant total de la ligne (calculé automatiquement)', max_digits=10, verbose_name='Montant')),
                ('devis', models.ForeignKey(help_text='Devis parent', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['numero'], name='devis_devis_numero_eb145b_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['date_creation'], name='devis_devis_date_cr_43b26d_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['statut'], name='devis_devis_statut_a30d19_idx'),
        ),
    ]
